typography_spectrum: 0.8599180611781776
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.361330741783604
  lightness: 0.982670244993642
  saturation: 0.5676576646510512
  rhythmicContrast: 0.13453755900263786
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7307221002411097
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Stacie
  email: stacie@staciearellano.com
name: Metahari
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Prime Avatar of Avataria
purpose: []
